export const node = [
  {
    id: 1,
    nombre: "PATARASHCA",
    correo: "hola",
    razon_social: "Hombre",
    ruc: "12022004",
    telefono: "901981127",
    sitio_web: "www.patasahrca.com",
  },
  {
    id: 2,
    nombre: "PATARASHCAII",
    correo: "hola",
    razon_social: "Hombre",
    ruc: "12022004",
    telefono: "901981127",
    sitio_web: "www.patasahrca.com",
  },
  {
    id: 3,
    nombre: "PATARASHCA",
    correo: "hola",
    razon_social: "Hombre",
    ruc: "12022004",
    telefono: "901981127",
    sitio_web: "www.patasahrca.com",
  },
  {
    id: 4,
    nombre: "COLLPA",
    correo: "hola",
    razon_social: "Hombre",
    ruc: "12022004",
    telefono: "901981127",
    sitio_web: "www.patasahrca.com",
  },
  {
    id: 5,
    nombre: "PATARASHCAI",
    correo: "hola",
    razon_social: "Hombre",
    ruc: "12022004",
    telefono: "901981127",
    sitio_web: "www.patasahrca.com",
  },
];
