export const comprasPaths = [
  {
    id: 1,
    name: "compras",
    path: "/compras",
    unionPath: "compras/",
    alias: "COMPRA",
  },
  {
    id: 2,
    name: "proveedores",
    path: "/proveedores",
    unionPath: "proveedores/",
    alias: "PROVEEDORES",
  },
  {
    id: 3,
    name: "registrar-proveedores",
    path: "/registrar-proveedores",
    unionPath: "registrar-proveedores/",
    alias: "CREAR PROVEEDOR",
  },
  {
    id: 4,
    name: "realizar-compra",
    path: "/realizar-compra",
    unionPath: "realizar-compra/",
    alias: "REALIZAR COMPRA",
  },
  {
    id: 5,
    name: "productos",
    path: "/productos",
    unionPath: "productos/",
    alias: "PRODUCTOS",
  },
  {
    id: 6,
    name: "almacen",
    path: "/almacen",
    unionPath: "almacen/",
    alias: "ALMACEN",
  },
  {
    id: 7,
    name: "detalle-compra",
    path: "/detalle-compra",
    unionPath: "detalle-compra/",
    alias: "DETALLE",
  },
  {
    id: 8,
    name: "insertar",
    path: "/insertar",
    unionPath: "insertar/",
    alias: "INSERTAR",
  },
];
