export const totalRoutes = [
  {
    id: 1,
    name: "prueba",
    path: "/prueba",
    unionPath: "prueba/",
    alias: "PRUEBA",
  },
  {
    id: 2,
    name: "prueba-dos",
    path: "/prueba-dos",
    unionPath: "prueba-dos/",
    alias: "PRUEBA DOS",
  },
  {
    id: 1,
    name: "compras",
    path: "/compras",
    unionPath: "compras/",
    alias: "COMPRA",
  },
  {
    id: 2,
    name: "proveedores",
    path: "/proveedores",
    unionPath: "proveedores/",
    alias: "PROVEEDORES",
  },
  {
    id: 3,
    name: "registrar-proveedores",
    path: "/registrar-proveedores",
    unionPath: "registrar-proveedores/",
    alias: "CREAR PROVEEDOR",
  },
  {
    id: 4,
    name: "realizar-compra",
    path: "/realizar-compra",
    unionPath: "realizar-compra/",
    alias: "REALIZAR COMPRA",
  },
  {
    id: 5,
    name: "productos",
    path: "/productos",
    unionPath: "productos/",
    alias: "PRODUCTOS",
  },
  {
    id: 6,
    name: "almacen",
    path: "/almacen",
    unionPath: "almacen/",
    alias: "ALMACEN",
  },
  {
    id: 7,
    name: "detalle-compra",
    path: "/detalle-compra",
    unionPath: "detalle-compra/",
    alias: "DETALLE",
  },
  {
    id: 8,
    name: "insertar",
    path: "/insertar",
    unionPath: "insertar/",
    alias: "INSERTAR",
  },
  // {
  //   id: 3,
  //   name: "login",
  //   path: "/login",
  //   unionPath: "login/",
  //   alias: "INICIAR SESIÓN",
  // },
  // {
  //   id: 4,
  //   name: "restore-password",
  //   path: "/restore-password",
  //   unionPath: "restore-password/",
  //   alias: "RESTABLECER CONTRASEÑA",
  // },
  // {
  //   id: 5,
  //   name: "update-password",
  //   path: "/update-password/:id",
  //   unionPath: "update-password/:id",
  //   alias: "ACTUALIZAR CONTRASEÑA",
  // },
];
