export const totalRoutes = [
  {
    id: 1,
    name: "lista-mesas",
    path: "/lista-mesas",
    unionPath: "lista-mesas/",
    alias: "LISTA DE MESAS",
  },
  {
    id: 2,
    name: "comedor",
    path: "/comedor",
    unionPath: "comedor/",
    alias: "COMEDOR",
  },
  {
    id: 6,
    name: "establecimiento",
    path: "/establecimiento",
    unionPath: "establecimiento/",
    alias: "ESTABLECIMIENTO",
  },
  {
    id: 7,
    name: "sucursales",
    path: "/sucursales",
    unionPath: "sucursales/",
    alias: "SUCURSALES",
  },
  // {
  //   id: 3,
  //   name: "login",
  //   path: "/login",
  //   unionPath: "login/",
  //   alias: "INICIAR SESIÓN",
  // },
  // {
  //   id: 4,
  //   name: "restore-password",
  //   path: "/restore-password",
  //   unionPath: "restore-password/",
  //   alias: "RESTABLECER CONTRASEÑA",
  // },
  // {
  //   id: 5,
  //   name: "update-password",
  //   path: "/update-password/:id",
  //   unionPath: "update-password/:id",
  //   alias: "ACTUALIZAR CONTRASEÑA",
  // },
];
